# /opt/docker-compose.yml
#
# new containers should follow this format:
# {ContainerName}:
#   image: {ImageName}:latest
#   container_name: {ContainerName}
#   volumes:
#     - /dir/on/host:/dir/within/container
#   ports:
#     - {ExternalPort}:{internalContainerPort} # This should generally be default per container
#   networks:
#     - {NetworkName} #found at bottom of doc "traefik_proxy1" if container will be exposed
#   labels:
#     - "traefik.enable={true | false}"
#     - "traefik.backend={ContainerName}"
#     - "traefik.frontend.rule=Host:{URLprefix}.${DOMAINNAME}"
#     - "traefik.port={ExternalPort}"
---
---
version: "3.4"
# Basic function 
x-external_default: &template_external
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
  networks:
    - traefik_proxy1
  restart: unless-stopped

x-internal_default: &template_internal
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
  volumes:
    - /opt/appdata/shared:/shared
  restart: unless-stopped
  labels:
    - "docker.group=internal"

services:
    traefik:
      <<: *template_external
      hostname: traefik
      image: traefik:v2.2
      container_name: traefik
      domainname: ${DOMAINNAME}
      networks:
        - default
      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
      labels:
        - "docker.group=external"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /home/dockeruser/traefik:/etc/traefik
        - /opt/appdata/shared:/shared
        - /opt/appdata/traefik:/var/log
        - /opt/appdata/traefik/tmp:/tmp    
      command:
        - --providers.docker
        - --entrypoints.web.address=:80
        - --providers.docker.network=traefik_proxy1
        - --entrypoints.websecure.address=:443
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - '--providers.docker.defaultRule=Host(`{{ normalize .Name }}.${DOMAINNAME}`)'
        # - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
        # - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=cloudflare"
        # - "--certificatesresolvers.mydnschallenge.acme.email=postmaster@example.com"
        # - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"

#Manager, Used to maintain docker containers  
  portainer:
    <<: *template_external
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      - traefik_proxy1
    labels:
      - "traefik.enable=false"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy1"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "docker.group=external"

#Networks, Needed for Traefik    
networks:
  traefik_proxy1:
      external: true